### ISSUE TITLE
Doesnt work on big sur

### ISSUE THREAD

**Issue by carlosxfigueroa** [cdf/Innie#1]
any chance of getting this working on big sur?

**Comment by yhl452493373** [comment]
> any chance of getting this working on big sur?

i found a way to make it work.you need to add -inniebeta to nvram -> boot-args

**Comment by yhl452493373** [comment]
> any chance of getting this working on big sur?

or download it here [innie 1.2.2](https://github.com/yhl452493373/Innie/releases/tag/v1.2.2)

**Comment by cdf** [comment]
Innie should now work on Big Sur. The extension has been rewritten so that it no longer depends on Lilu.

**Comment by tanpengsccd** [comment]
not work too for Bigsur. and catalina work. with 1.3.0 release
