### ISSUE TITLE
Does not work on big sur 11.2.1?

### ISSUE THREAD

**Issue by wdrich** [cdf/Innie#6]
Does not work on big sur 11.2.1

Please Fix this bug, Thank you!

**Comment by thomas22122212** [comment]
Works for me on 11.4. Maybe you did something wrong 🤷‍♂️
Did you properly add it to your OC config?

**Comment by DoctorDan1986** [comment]
Always fails at:

daniel@Daniels-Mac-Pro ~ % sudo mount -uw /  
Password:
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66

**Comment by cdf** [comment]
This is a configuration issue.
