### ISSUE TITLE
v1.3.0 requires reboot after install to work on Catalina 10.15.7

### ISSUE THREAD

**Issue by SemoTech** [cdf/Innie#7]
Seems latest version Innie v1.3.0 errors out in Catalina with SIP disabled. ==> Solved, see below....

![image](https://user-images.githubusercontent.com/1452100/119731385-b8e7c400-be2b-11eb-981a-4df88f275bbb.png)

Any suggestions?

**Comment by cdf** [comment]
If you're referring to the warning, that's normal in Catalina. After rebooting, you can check that the kext is loaded in System Information > Extensions.

**Comment by SemoTech** [comment]
Darn!  I figured it failed and fully removed it.  Guess I will re-do everything again and retry. Will update if it works. 

**_WORKED!!!!  Awesome Sauce!  Thanks a bunch!_**

For reference my NVMe is a:  **Sabrent Rocket Q 2TB** unit installed internally via a PCIe adapter. 

Hackintool reports it as:  IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IOU1@7/IOPP/PXS2@0/IOPP/pci-bridge@6/IOPP/pci1987,5012@0

System profiler under PCIe shows:

pci1987,5012:

  Type:	NVM Express Controller
  Driver Installed:	Yes
  MSI:	Yes
  Bus:	PCI
  Slot:	Slot-2@13,0,0
  Vendor ID:	0x1987
  Device ID:	0x5012
  Subsystem Vendor ID:	0x1987
  Subsystem ID:	0x5012
  Revision ID:	0x0001
  Serial Number:	24FF0613459710202865
  Link Width:	x4
  Link Speed:	5.0 GT/s

**Comment by SemoTech** [comment]
Only problem I still have is that I cannot change the icon of the drive, it's defaulted to the internal drive now.  Any attempt to edit and paste a new icon from another drive, or even moving a new ".VolumeIcon.icns" file in the root will not change it.

Any suggestions?

**Comment by cdf** [comment]
Strange. On my end, the kext doesn't prevent changing the icon, and nor should it. Differences in behavior between internal and external drives is controlled by macOS.

**Comment by SemoTech** [comment]
> Strange. On my end, the kext doesn't prevent changing the icon, and nor should it. Differences in behavior between internal and external drives is controlled by macOS.

Yes, I do not believe this is an issue with your kext @cdf I think its the fact that Catalina still things this is an external drive and has locked the icon.  I tried everything and no luck...

**Comment by SemoTech** [comment]
One more weird thing @cdf, and this may be related to the kext:

I have an Amftec Squid PCIe x16 Gen 2 board able to run 4 M2 blades in the Mac Pro 5,1
On it I have 3 x 512GB Samsung's and 1 x  2TB Sabrent Rocket Q.

Following the kext install, both the 2TB Sabrent and one of the Samsung blades have been marked as Internal drives, but the remaining 2 Samsung 512GB blades, on the same Amftec Squid are still showing as External "yellow".

Any ideas why and how to show them all as Internal?

Thanks.

**Comment by cdf** [comment]
Yes, there is currently a bug that makes Innie miss some drives. The reason is that the kext is a little too zealous in getting out of the way. The next update should address this.

**Comment by SemoTech** [comment]
> Yes, there is currently a bug that makes Innie miss some drives. The reason is that the kext is a little too zealous in getting out of the way. The next update should address this.

Phew, so glad you are aware of this.  Looking forward to the next update.  Thank you.
